"""create orders/position table

Revision ID: fcaf9f50251a
Revises: 
Create Date: 2026-05-19 13:21:14.835697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcaf9f50251a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='tradeside'), nullable=True),
    sa.Column('order_type', sa.Enum('LIMIT', 'MARKET', 'TAKE_PROFIT', 'STOP_LOSS', 'CONDITIONAL', 'UNKNOWN', name='ordertype'), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'NEW', 'CLOSED', 'CANCELED', 'EXPIRED', 'REJECTED', 'TRIGGERED', 'UNTRIGGERED', 'ACTIVE', 'PARTIALLY_FILLED', 'UNKNOWN', 'DEACTIVATED', 'FILLED', name='orderstatus'), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('trigger_price', sa.Float(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('filled', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('order_link_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_account_name'), 'orders', ['account_name'], unique=False)
    op.create_index(op.f('ix_orders_message_id'), 'orders', ['message_id'], unique=False)
    op.create_index(op.f('ix_orders_order_type'), 'orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='tradeside', native_enum=False), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('sl_state', sa.Enum('INITIAL', 'BREAKEVEN', 'TRAILED_TP1', name='stoplossstate', native_enum=False), server_default='initial', nullable=False),
    sa.Column('current_sl_order_id', sa.String(), nullable=True),
    sa.Column('highest_tp_hit', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('is_sl_updated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('account_name', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_message_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_account_name'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
