from typing import Protocol

from trading_bot.core.application.database.dto.order import OrderDTO


class OrderRepositoryProtocol(Protocol):
    async def upsert(self, order: OrderDTO) -> None: ...

    async def get_by_id(self, order_id: str) -> OrderDTO | None: ...
    async def get_active_orders(self, symbol: str | None = None) -> list[OrderDTO]: ...
    async def get_stop_loss_by_symbol(self, symbol: str) -> OrderDTO | None: ...
    async def get_takeprofits_by_symbol(self, symbol: str) -> list[OrderDTO] | None: ...
    async def get_stop_loss_by_signal(self, account_name: str, message_id: str) -> OrderDTO | None: ...
    async def get_takeprofits_by_signal(self, account_name: str, message_id: str) -> list[OrderDTO]: ...
    async def get_by_link_id(self, order_link_id: str) -> OrderDTO | None: ...

    async def delete_by_symbol(self, symbol: str) -> bool: ...
    async def delete_by_symbol_and_account(self, account_name: str, symbol: str) -> bool: ...
    async def delete_by_id(self, order_id: str) -> bool: ...
    async def delete_by_link_id(self, order_link_id: str) -> bool: ...
