x-default-tp-distributions: &default_tp
    3:
        - { level: 1, close_size: 0.5 }
        - { level: 2, close_size: 0.3 }
        - { level: 3, close_size: 0.2 }
    4:
        - { level: 1, close_size: 0.4 }
        - { level: 2, close_size: 0.3 }
        - { level: 3, close_size: 0.2 }
        - { level: 4, close_size: 0.1 }
    5:
        - { level: 1, close_size: 0.3 }
        - { level: 2, close_size: 0.25 }
        - { level: 3, close_size: 0.2 }
        - { level: 4, close_size: 0.15 }
        - { level: 5, close_size: 0.1 }
general:
    mode: production
discord:
    sources:
        - source_name: elite
          enabled: true
          channel_id: 1489620284548976751
          accounts:
              - account: account1
              - account: account2
              - account: account3
          leverage: 5
          default_sl: 0.032
          tp_distributions: *default_tp
        - source_name: algo
          enabled: true
          channel_id: 1499863184360870069
          accounts:
              - account: account1
              - account: account2
              - account: account3
          leverage: 5
          default_sl: 0.032
          tp_distributions: *default_tp
        - source_name: andre
          enabled: true
          channel_id: 1489620301691228290
          accounts:
              - account: account1
              - account: account2
              - account: account3
          leverage: 5
          default_sl: 0.032
          tp_distributions: *default_tp
        - source_name: haseeb
          enabled: true
          channel_id: 1489620313351393502
          accounts:
              - account: account1
              - account: account2
              - account: account3
          leverage: 5
          default_sl: 0.032
          tp_distributions: *default_tp
        - source_name: voyager
          enabled: true
          channel_id: 1506346501138288700
          accounts:
              - account: account1
              - account: account2
              - account: account3
          leverage: 5
          default_sl: 0.032
          tp_distributions: *default_tp
accounts:
    account1:
        exchange: bybit
        demo: true
        position_size: 0.005
        timeout_seconds: 15
    account2:
        exchange: bybit
        demo: true
        position_size: 0.1
        timeout_seconds: 15
    account3:
        exchange: bybit
        demo: true
        position_size: 0.1
        timeout_seconds: 15
