from collections.abc import Awaitable, Callable
from typing import Protocol

from trading_bot.core.application.database.dto import PositionDTO
from trading_bot.core.application.trading.dto import EventDTO, PlacedOrderDTO, PlaceOrderDTO
from trading_bot.core.domain.value_objects.symbol import SymbolInfo
from trading_bot.core.domain.value_objects.trading import TradeSide


class ExchangeGatewayProtocol(Protocol):
    account_name: str

    @property
    def name(self) -> str: ...

    async def get_last_price(self, symbol: str) -> float: ...
    async def get_balance(self) -> float: ...
    async def get_position(self, symbol: str) -> PositionDTO | None: ...
    async def get_symbol_info(self, symbol: str) -> SymbolInfo: ...
    async def get_orders(self, symbol: str) -> list[PlacedOrderDTO] | None: ...

    async def place_order(self, request: PlaceOrderDTO) -> PlacedOrderDTO: ...
    async def place_market_order(self, symbol: str, side: TradeSide, qty: float | str) -> PlacedOrderDTO: ...
    async def place_limit_order(self, symbol: str, price: float, side: TradeSide, qty: float | str) -> PlacedOrderDTO: ...
    async def place_stop_loss_order(self, symbol: str, side: TradeSide, stop_price: float, link_id: str | None = None) -> PlacedOrderDTO: ...
    async def place_conditional_market_order(self, symbol: str, side: TradeSide, qty: float | str, trigger_price: float) -> PlacedOrderDTO: ...
    async def place_orders(self, requests: list[PlaceOrderDTO]) -> list[PlacedOrderDTO]: ...
    async def place_trade_setup(self, orders: list[PlaceOrderDTO]) -> list[PlacedOrderDTO]: ...

    async def cancel_all_orders(self, symbol: str) -> bool: ...
    async def cancel_order(self, symbol: str, order_id: str) -> bool: ...
    async def cancel_order_by_link_id(self, symbol: str, order_link_id: str) -> bool: ...
    async def cancel_position(self, symbol: str, side: TradeSide, qty: float): ...
    async def listen_user_stream(self, on_update_callback: Callable[[EventDTO], Awaitable[None]]) -> None: ...

    async def close(self) -> None: ...


class ExchangeRegistryProtocol(Protocol):
    def get_exchange(self, name: str) -> ExchangeGatewayProtocol: ...
    def get_all_exchanges(self) -> list[ExchangeGatewayProtocol]: ...

    async def listen_user_stream(self, on_update_callback: Callable[[EventDTO], Awaitable[None]]) -> None: ...
